title: Griffin Shea # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Carleton University Graduate<br>
  School of Computer Science<br>
  Computer Game Development<br>
  <br>
  This page showcases a few of my game projects.<br>
  All work is my own unless noted otherwise.<br>
  <br>
  griffin.shea@carleton.ca<br>
  <br>
  
theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
