title:
    Griffin Shea<br>
	Carleton University Graduate<br>
	School of Computer Science<br>
	Computer Game Development Stream<br>
    Minor in History<br>
    
logo: "/images/logo.png?raw=true"

description:
    <br>
	This page showcases a few of my game projects.<br>
	All work is my own unless noted otherwise.<br>
	<br>
	Contact me: <a href="griffin.shea@carleton.ca">griffin.shea@carleton.ca</a><br>
	<br>
  
theme: jekyll-theme-minimal

